# My comment
# My comment
name: my-github-actions-workflow
env:
  APPLICATION_NAME    : "My-Flask-${{ github.workflow}}"
  DEPLOY_PACKAGE_NAME : "My-deploy-vers-${{ github.sha}}"
  
# Controls when the workflow will run 
on:  
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:

  My-testing-job:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Step1_Print_Hello (My-testing-job)
        run: echo "Hello world Test"
      - name: Step1_Execute few commands
        run: |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name: ${{ env.APPLICATION_NAME}}"
          
  My-deploy-job:
  
    runs-on: ubuntu-latest 
    needs: [My-testing-job] 
    
    steps:
      - name: Step2_Print Hello (My-deploy-job)
        run: echo Hello World Deploy
      - name: Step2_Printing depl package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME}}"
