# My comment
# My comment
name: my-github-actions-workflow

# Controls when the workflow will run
on:
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:

  my-testing-job:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello (test)
        run: echo "Hello world Test"
     
  my-deploy-job:
  
    runs-on: ubuntu-latest 
    needs: [my-testing-job]
    
    steps:
      - name: Print Hello (deploy)
        run: echo Hello World Deploy
