# My comment
# My comment
name: my-github-actions-workflow
env:
  APPLICATION_NAME    : "My-Flask"
  DEPLOY_PACKAGE_NAME : "My-deploy-vers-${{ githab.sha}}"

# Controls when the workflow will run 
on:  
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:

  my-testing-job:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello (test)
        run: echo "Hello world Test"
      - name: Execute few commands
        run: |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name: ${{ env.APPLICATION_NAME}}"
          
  my-deploy-job:
  
    runs-on: ubuntu-latest 
    needs: [my-testing-job] 
    
    steps:
      - name: Print Hello (deploy)
        run: echo Hello World Deploy
      - name: Printing depl package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME}}"
