# My comment
# My comment
name: My-github-actions-workflow
env:
  APPLICATION_NAME    : "My-Flask-${{ github.workflow}}"
  DEPLOY_PACKAGE_NAME : "My-deploy-vers-${{ github.sha}}"
  
# Controls when the workflow will run 
on:  
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

jobs:

  My-testing-job:
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Step1_Print_Hello (My-testing-job)
        run: echo "Hello world Test"
        
      - name: Step2_Execute few commands
        run: |
          echo "Hello message 1"
          echo "Hello message 2"
          echo "Application name: ${{ env.APPLICATION_NAME}}"
      
      - name: Step3_clone_my_repo
        uses: actions/checkout@v1
      
      - name: Step4_list_folder
        run: ls -la
          
  My-deploy-job:
  
    runs-on: ubuntu-latest 
    needs: [My-testing-job] 
    env:
      VAR1 : "Ths is job level var1"
    
    steps:    
      - name: Step1_Print Hello (My-deploy-job)
        run: echo Hello World Deploy
        
      - name: Step2_Printing depl package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME}}"
        
      - name: Step3_Lets test some package if they are here 1
        run: aws --version

      - name: Step4_Lets test some package if they are here 2
        run: zip --version
        
      - name: Step4_print local variables
        run : |
          echo "var1 = ${{ env.VAR1" }}"
          echo "var_step1 = $VAR_STEP1
        env:
          VAR_STEP1 : "This is a step level var"
          
